from distutils.core import setup

setup(
    name='tecbox',
    version='1.0.0',
    packages=['service.api', 'service.venv.Lib.site-packages.click', 'service.venv.Lib.site-packages.flask',
              'service.venv.Lib.site-packages.flask.json', 'service.venv.Lib.site-packages.jinja2',
              'service.venv.Lib.site-packages.werkzeug', 'service.venv.Lib.site-packages.werkzeug.debug',
              'service.venv.Lib.site-packages.werkzeug.contrib', 'service.venv.Lib.site-packages.markupsafe',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'service.venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='https://github.com/joexd/tecbox',
    license='MIT',
    author='joexd',
    author_email='bbyecy@gmail.com',
    description='Collaboration Plattform for Learning'
)
